apiVersion: v1
appVersion: "v1.5.0" # x-release-please-version
version: 0.1.1
name: openfaas-loki
description: A Loki powered log provider for OpenFaaS
maintainers:
  - name: Lucas Roesler
    url: https://lucasroesler.com
