name: Lint and Test Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/**
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - charts/**

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Lint
        run: helm lint --strict charts/openfaas-loki --set lokiURL=http://loki.default
