on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          # use the CI token to pretend not to be a action
          token: ${{ secrets.CI_RELEASER_TOKEN }}
          release-type: go
          package-name: ""
          extra-files: |
            chart/Chart.yaml
            chart/values.yaml
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"docs","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Miscellaneous","hidden":false}
            ]
      - name: Debug release output
        run: |
          echo '${{ toJSON(steps.release.outputs) }}'
